### ISSUE TITLE
needs tests!

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/intro-to-rake#2]
Needs tests to make sure students completed this walk through

**Comment by AnnJohn** [comment]
is this still an open issue @SophieDeBenedetto?

**Comment by SophieDeBenedetto** [comment]
yes

**Comment by bhollan** [comment]
Let me know when this issue is resolved so I can get this green dot!  :)

**Comment by SophieDeBenedetto** [comment]
hi @bhollan, this issue is resolved, this lab now has tests. if you pulled down this lab before it was updated two days ago, you can grab the most recent version by running the following in your command line in the directory of this project:

1. `git remote add upstream git@github.com:learn-co-curriculum/intro-to-rake.git`
2. `git pull origin upstream`
3. `git remote -rm upstream`

**Comment by bhollan** [comment]
Something strange must have happened.  I've actually had this happen a couple of times so far.  In going through the material, it will actually either A) fork/clone incompletely B) fork/clone the wrong repo C) fork/clone the wrong version of a repo.

I just checked and I did this lab earlier today.  The copy that was forked/cloned through the automation did not function correctly.  See for yourself:
https://github.com/bhollan/intro-to-rake-v-000

Even when I ran the commands listed in your comments, it didn't update properly.

But when I manually deleted and re-cloned this repo directly from here, it worked and looks like it does on github.  The tests also run and pass, but the light for this lesson did not go green.

I suspect that the green light is an obvious reason like it's pointing to the old fork or something.  But I will leave things as they are if you want to browse the old fork.

I'm probably just going to leave it as it is.  It's not the first green light that has refused to turn on and it probably won't be the last.  I care about learning the material and it has been stupendous thus far.

Let me know if there's any further debugging I can help with!  :)

**Comment by SophieDeBenedetto** [comment]
Hi @bhollan, thanks for elaborating on this issue. I will pass this along to our team. have a good weekend!

**Comment by vicfriedman** [comment]
hey @bhollan,

I went ahead and closed this issue because it seems like it's more of an engineering problem than a curriculum problem. Could you also go ahead and open a bug report for our engineering team to take a look at your issues?
