### ISSUE TITLE
rake greeting:hello example does not work

### ISSUE THREAD

**Issue by IshmaelKhalid** [learn-co-curriculum/intro-to-rake#22]
Now, in your terminal in the directory of this project, type:
rake greeting:hello
You should see the following outputted to your terminal:
hello from Rake!

-----------------------------------------------------------------------------
This example does not work because we have not given the namespace to our rakefile yet.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by IshmaelKhalid** [comment]
I understand. The issue i raised is a "content" issue, as the content that would allow the commands to work is not presented in the correct order. Therefore,  following the lesson from top to bottom the commands do not work.


Get Outlook for Android






On Sun, Jun 26, 2016 at 4:18 PM -0400, "Charles Pletcher" <notifications@github.com> wrote:












Thanks for opening this issue!



Keep in mind that this space is for specific issues related to the content of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)



Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
