### ISSUE TITLE
Inheriting without Rails version target raises error.

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/intro-to-rake#26]
**ERROR**
DEPRECATION WARNING: Directly inheriting from ActiveRecord::Migration is deprecated. Please specify the Rails release the migration was written for:

**SOLUTION**
Placing the integer value of the version # of Rails in brackets at the end of statement satisfies requirement.

(ex.) class CreateArtists < ActiveRecord::Migration[4.2]

**Comment by gj** [comment]
Are you on Rails 4 or Rails 5?

**Comment by sgharms** [comment]
Based on this discussion, and the fact that `ActiveRecord::Migration` isn't used in this challenge, I'm going to close this as pointing to the wrong lesson.
