### ISSUE TITLE
Suggestion for Right Column on Learn Lessons/Labs

### ISSUE THREAD

**Issue by psnider30** [learn-co-curriculum/intro-to-rake#27]
This suggestion is  not specific to this lab.

I would find it convenient if the right column could be collapsed or made hidden since I like to use the README in the browser side by side with my text editor. If I could hide the column with the Questions and Tests then I could utilize monitor space better and more easily than manually dragging windows. I was thinking of a toggle arrow, but anyway to hide the column would be helpful.  Anyways, just an idea.

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface improvements. You can reach them at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue and we will try to discern a proper path to resolution.
