### ISSUE TITLE
confusing

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/intro-to-rake#32]
task console => environment and task environment work outside of namespace db but not inside it.

There is no clear cut direction on where to place it, and the with the last instruction being db:seed it is automatically assumed it should be in namespace :db.

please fix the readme

source -Chris Henry tech coach 9/13

**Comment by sgharms** [comment]
@BenitolSantos 

I'm having some trouble understanding your request here.

> task console => environment and task environment work outside of namespace db but not inside it.

```ruby
task :environment do
  puts "running environment"
  require_relative './config/environment'
end

namespace :db do
  desc 'migrate changes to your database'
  task :migrate => :environment do
    puts "running migrate"
  end
end
```

generates....

```text
$ rake db:migrate
running environment
running migrate
```

as expected.

Also the section that introduces `:seed` shows that it's within a namespace bloc.

At this point, I can't reproduce your issue. If you can re-open this issue with screenshots (maybe?) or refer to specific quoted text in the README we can likely fix it.
