### ISSUE TITLE
The rspec tests are missing a test for "rake console".

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/intro-to-rake#34]
Hello. The README had us make a task for Rake called :console, but there isn't an rspec test for that. I don't know if that was intentional or not, but I wanted to let you guys know.

Thanks for checking this out, and Happy Holidays!

Sdcrouse

**Comment by sgharms** [comment]
Added in #35! Thanks.

**Comment by Sdcrouse** [comment]
Not a problem. Thanks for doing that!
